"""modify user table &add dilivery table

Revision ID: 06a1fb04cc4a
Revises: 77d1a1e54811
Create Date: 2018-01-20 14:35:33.766369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06a1fb04cc4a'
down_revision = '77d1a1e54811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('response', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_job',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('registrations')
    op.add_column('user', sa.Column('upload_resume_ulr', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_fullname', table_name='user')
    op.drop_index('ix_user_phone_num', table_name='user')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'phone_num')
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('fullname', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('user', sa.Column('phone_num', mysql.VARCHAR(length=32), nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_phone_num', 'user', ['phone_num'], unique=True)
    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=True)
    op.drop_column('user', 'upload_resume_ulr')
    op.create_table('registrations',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='registrations_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='registrations_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_job')
    op.drop_table('delivery')
    # ### end Alembic commands ###
