"""job table add salary_low&high

Revision ID: 10f9e057d94f
Revises: 99a5252b1638
Create Date: 2018-01-21 19:28:11.021968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10f9e057d94f'
down_revision = '99a5252b1638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary_high', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('salary_low', sa.Integer(), nullable=False))
    op.drop_column('job', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('job', 'salary_low')
    op.drop_column('job', 'salary_high')
    # ### end Alembic commands ###
