"""modify company table

Revision ID: 77d1a1e54811
Revises: 3a340798aa5a
Create Date: 2018-01-20 13:38:39.055079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d1a1e54811'
down_revision = '3a340798aa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('field', sa.String(length=32), nullable=True))
    op.add_column('company', sa.Column('financeStage', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'financeStage')
    op.drop_column('company', 'field')
    # ### end Alembic commands ###
