"""modify company table

Revision ID: cd076d7133ae
Revises: 06a1fb04cc4a
Create Date: 2018-01-21 18:38:43.965906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd076d7133ae'
down_revision = '06a1fb04cc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###
